// Generated by gencpp from file moveit_interface/RobotControl.msg
// DO NOT EDIT!


#ifndef MOVEIT_INTERFACE_MESSAGE_ROBOTCONTROL_H
#define MOVEIT_INTERFACE_MESSAGE_ROBOTCONTROL_H

#include <ros/service_traits.h>


#include <moveit_interface/RobotControlRequest.h>
#include <moveit_interface/RobotControlResponse.h>


namespace moveit_interface
{

struct RobotControl
{

typedef RobotControlRequest Request;
typedef RobotControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotControl
} // namespace moveit_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_interface::RobotControl > {
  static const char* value()
  {
    return "f4178e569aa36a63f67d15ee7547eaac";
  }

  static const char* value(const ::moveit_interface::RobotControl&) { return value(); }
};

template<>
struct DataType< ::moveit_interface::RobotControl > {
  static const char* value()
  {
    return "moveit_interface/RobotControl";
  }

  static const char* value(const ::moveit_interface::RobotControl&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_interface::RobotControlRequest> should match 
// service_traits::MD5Sum< ::moveit_interface::RobotControl > 
template<>
struct MD5Sum< ::moveit_interface::RobotControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_interface::RobotControl >::value();
  }
  static const char* value(const ::moveit_interface::RobotControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_interface::RobotControlRequest> should match 
// service_traits::DataType< ::moveit_interface::RobotControl > 
template<>
struct DataType< ::moveit_interface::RobotControlRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_interface::RobotControl >::value();
  }
  static const char* value(const ::moveit_interface::RobotControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_interface::RobotControlResponse> should match 
// service_traits::MD5Sum< ::moveit_interface::RobotControl > 
template<>
struct MD5Sum< ::moveit_interface::RobotControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_interface::RobotControl >::value();
  }
  static const char* value(const ::moveit_interface::RobotControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_interface::RobotControlResponse> should match 
// service_traits::DataType< ::moveit_interface::RobotControl > 
template<>
struct DataType< ::moveit_interface::RobotControlResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_interface::RobotControl >::value();
  }
  static const char* value(const ::moveit_interface::RobotControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_INTERFACE_MESSAGE_ROBOTCONTROL_H
