// Generated by gencpp from file moveit_interface/RobotControlResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_INTERFACE_MESSAGE_ROBOTCONTROLRESPONSE_H
#define MOVEIT_INTERFACE_MESSAGE_ROBOTCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_interface
{
template <class ContainerAllocator>
struct RobotControlResponse_
{
  typedef RobotControlResponse_<ContainerAllocator> Type;

  RobotControlResponse_()
    : execute_result(false)  {
    }
  RobotControlResponse_(const ContainerAllocator& _alloc)
    : execute_result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _execute_result_type;
  _execute_result_type execute_result;





  typedef boost::shared_ptr< ::moveit_interface::RobotControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_interface::RobotControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotControlResponse_

typedef ::moveit_interface::RobotControlResponse_<std::allocator<void> > RobotControlResponse;

typedef boost::shared_ptr< ::moveit_interface::RobotControlResponse > RobotControlResponsePtr;
typedef boost::shared_ptr< ::moveit_interface::RobotControlResponse const> RobotControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_interface::RobotControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveit_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_interface::RobotControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_interface::RobotControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_interface::RobotControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dc59600a84b2d1d08b552ecdd8c7473";
  }

  static const char* value(const ::moveit_interface::RobotControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dc59600a84b2d1dULL;
  static const uint64_t static_value2 = 0x08b552ecdd8c7473ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_interface/RobotControlResponse";
  }

  static const char* value(const ::moveit_interface::RobotControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool execute_result\n\
\n\
";
  }

  static const char* value(const ::moveit_interface::RobotControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execute_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_interface::RobotControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_interface::RobotControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "execute_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_INTERFACE_MESSAGE_ROBOTCONTROLRESPONSE_H
