// Generated by gencpp from file interface/ControlRobotResponse.msg
// DO NOT EDIT!


#ifndef INTERFACE_MESSAGE_CONTROLROBOTRESPONSE_H
#define INTERFACE_MESSAGE_CONTROLROBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interface
{
template <class ContainerAllocator>
struct ControlRobotResponse_
{
  typedef ControlRobotResponse_<ContainerAllocator> Type;

  ControlRobotResponse_()
    : execute_result(false)  {
    }
  ControlRobotResponse_(const ContainerAllocator& _alloc)
    : execute_result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _execute_result_type;
  _execute_result_type execute_result;





  typedef boost::shared_ptr< ::interface::ControlRobotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interface::ControlRobotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlRobotResponse_

typedef ::interface::ControlRobotResponse_<std::allocator<void> > ControlRobotResponse;

typedef boost::shared_ptr< ::interface::ControlRobotResponse > ControlRobotResponsePtr;
typedef boost::shared_ptr< ::interface::ControlRobotResponse const> ControlRobotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interface::ControlRobotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interface::ControlRobotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::interface::ControlRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interface::ControlRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::ControlRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::ControlRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::ControlRobotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::ControlRobotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interface::ControlRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dc59600a84b2d1d08b552ecdd8c7473";
  }

  static const char* value(const ::interface::ControlRobotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dc59600a84b2d1dULL;
  static const uint64_t static_value2 = 0x08b552ecdd8c7473ULL;
};

template<class ContainerAllocator>
struct DataType< ::interface::ControlRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interface/ControlRobotResponse";
  }

  static const char* value(const ::interface::ControlRobotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interface::ControlRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool execute_result\n\
\n\
";
  }

  static const char* value(const ::interface::ControlRobotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interface::ControlRobotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execute_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlRobotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interface::ControlRobotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interface::ControlRobotResponse_<ContainerAllocator>& v)
  {
    s << indent << "execute_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACE_MESSAGE_CONTROLROBOTRESPONSE_H
