// Generated by gencpp from file interface/RobotControlRequest.msg
// DO NOT EDIT!


#ifndef INTERFACE_MESSAGE_ROBOTCONTROLREQUEST_H
#define INTERFACE_MESSAGE_ROBOTCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interface
{
template <class ContainerAllocator>
struct RobotControlRequest_
{
  typedef RobotControlRequest_<ContainerAllocator> Type;

  RobotControlRequest_()
    : type()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , virtual_debug(false)
    , extra()  {
    }
  RobotControlRequest_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , virtual_debug(false)
    , extra(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef uint8_t _virtual_debug_type;
  _virtual_debug_type virtual_debug;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _extra_type;
  _extra_type extra;





  typedef boost::shared_ptr< ::interface::RobotControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interface::RobotControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotControlRequest_

typedef ::interface::RobotControlRequest_<std::allocator<void> > RobotControlRequest;

typedef boost::shared_ptr< ::interface::RobotControlRequest > RobotControlRequestPtr;
typedef boost::shared_ptr< ::interface::RobotControlRequest const> RobotControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interface::RobotControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interface::RobotControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::interface::RobotControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interface::RobotControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::RobotControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::RobotControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::RobotControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::RobotControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interface::RobotControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63afc79bbd0942d5b9f0fe0a2cf7990a";
  }

  static const char* value(const ::interface::RobotControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63afc79bbd0942d5ULL;
  static const uint64_t static_value2 = 0xb9f0fe0a2cf7990aULL;
};

template<class ContainerAllocator>
struct DataType< ::interface::RobotControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interface/RobotControlRequest";
  }

  static const char* value(const ::interface::RobotControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interface::RobotControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
bool virtual_debug\n\
float64[] extra\n\
";
  }

  static const char* value(const ::interface::RobotControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interface::RobotControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.virtual_debug);
      stream.next(m.extra);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interface::RobotControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interface::RobotControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "virtual_debug: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.virtual_debug);
    s << indent << "extra[]" << std::endl;
    for (size_t i = 0; i < v.extra.size(); ++i)
    {
      s << indent << "  extra[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.extra[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACE_MESSAGE_ROBOTCONTROLREQUEST_H
